clc; close all;
b = (1/3) * [1, 1, 1];   
a = 1;                
N = 100;              
n = 0:(N-1);
x = 0.9 * ones(1, N);            
rng(0);                  
noise = 0.2 * randn(size(n));
xnoisy = x + noise;     
y = filter(b, a, xnoisy);
figure('Name', 'Frequency Response', 'NumberTitle', 'off');
[H, w] = freqz(b, a, 512);
subplot(2,1,1);
plot(w/pi, abs(H), 'Color', '#0072BD', 'LineWidth', 2);
title('Magnitude Response |H(e^{j\omega})|');
ylabel('Magnitude'); xlabel('\omega (\times\pi rad/sample)'); 
subplot(2,1,2);
plot(w/pi, angle(H), 'Color', '#D95319', 'LineWidth', 2);
title('Phase Response \angle H(e^{j\omega})');
ylabel('Phase in radians)'); xlabel('\omega (\times\pi rad/sample)');
figure('Name', 'Filtering Results', 'NumberTitle', 'off');
subplot(3,1,1);
stem(n, x, 'filled', 'MarkerFaceColor', '#0072BD', 'LineWidth', 1.2);
title('Original Clean Signal');
ylabel('Amplitude'); xlabel('n (samples)'); 
ylim([0 1.2]);
subplot(3,1,2);
plot(n, xnoisy, 'Color', '#D95319', 'LineWidth', 1.2);
title('Corrupted Signal');
ylabel('Amplitude'); xlabel('n (samples)'); 
subplot(3,1,3);
plot(n, y, 'Color', '#00FF66', 'LineWidth', 2); hold on;           
plot(n, x, '--', 'Color', '#FFFFFF', 'LineWidth', 1.8); hold off;  
title('Filtered Signal Output: y[n]');
ylabel('Amplitude'); xlabel('n (samples)');
legend('Filtered Output (y[n])', 'Original Signal (x[n])', ...
    'Location', 'best');
