clc; close all; 
N = 32;
n = 0:(N-1);
x = (0.5).^n;
Xdft = fft(x);
wdft = n * 2 * pi / N;
Ndtft = 512;
[Xdtft, wdtft] = freqz(x, 1, Ndtft, 'whole'); 
subplot(2,2,1); 
plot(wdtft, abs(Xdtft), 'b', 'LineWidth', 1.2); 
title('DTFT: Magnitude'); 
ylabel('magnitude'); xlabel('frequency \omega (rad)'); grid on;
subplot(2,2,3); 
plot(wdtft, angle(Xdtft), 'r', 'LineWidth', 1.2); 
title('DTFT: Phase'); 
ylabel('phase (rad)'); xlabel('frequency \omega (rad)'); grid on;
subplot(2,2,2); 
stem(wdft, abs(Xdft), 'filled', 'b'); 
title('DFT: Magnitude'); 
ylabel('magnitude'); xlabel('frequency \omega_k (rad)'); grid on;
subplot(2,2,4); 
stem(wdft, angle(Xdft), 'filled', 'r'); 
title('DFT: Phase'); 
ylabel('phase (rad)'); xlabel('frequency \omega_k (rad)'); grid on;
