clc; close all;
f = 50; Fs = 1000;
t = 0:(1/Fs):(20/f);
x = sin(2*pi*f*t);
X = fft(x,256);
subplot(211); stem(abs(X));
ylabel('magnitude');
title('DFT'); subplot(212);
stem(angle(X));
ylabel("phase"); xlabel("samples --->");
L = length(X)/2;
f = (0:L-1) * (Fs/2) / L;
figure;
subplot(211); plot(f,abs(X(1:L)));
ylabel('magnitude');
title('DTFT'); subplot(212);
plot(f, angle(X(1:L)));
xlabel('Frequency in Hz)');
ylabel('Phase');
