clc; close all; 
n = 0:10;                   
u = @(k) (k >= 0);
delta = @(k) (k == 0);
h = (0.5.^n) .* (u(n) - u(n-10));
xa = (0.8.^n) .* (u(n) - u(n-5));
xb = delta(n) + 3*delta(n-1) + 4*delta(n-3);
ya = conv(xa, h);
yb = conv(xb, h);
ya_10 = ya(1:length(n));
yb_10 = yb(1:length(n));
disp('n:'); disp(n);
disp('Output y_a[n] (for 0 <= n <= 10):'); disp(round(ya_10, 4));
disp('Output y_b[n] (for 0 <= n <= 10):'); disp(round(yb_10, 4));
subplot(3,2,1); stem(n, h, 'filled');
title('Impulse Response: h[n] = (0.5)^n \{u[n] - u[n-10]\}');
ylabel('amplitude'); xlabel('n--->'); grid on; 
subplot(3,2,3); stem(n, xa, 'filled');
title('Input (a): x_a[n] = (0.8)^n \{u[n] - u[n-5]\}');
ylabel('amplitude'); xlabel('n--->'); grid on; 
subplot(3,2,5); stem(n, ya_10, 'filled');
title('Output (a): y_a[n] (0 \leq n \leq 10)');
ylabel('amplitude'); xlabel('n--->'); grid on;
subplot(3,2,2); stem(n, h, 'filled');
title('Impulse Response: h[n] = (0.5)^n \{u[n] - u[n-10]\}');
ylabel('amplitude'); xlabel('n--->'); grid on; 
subplot(3,2,4); stem(n, xb, 'filled');
title('Input (b): x_b[n] = \delta[n] + 3\delta[n-1] + 4\delta[n-3]');
ylabel('amplitude'); xlabel('n--->'); grid on; 
subplot(3,2,6); stem(n, yb_10, 'filled');
title('Output (b): y_b[n] (0 \leq n \leq 10)');
ylabel('amplitude'); xlabel('n--->'); grid on;
