clc; close all;
b = [1, 0, -1];  
a = [1, -6, 9];
n = -15:15;      
u = @(k) (k >= 0);
h = -(1/9)*(n == 0) - (1/9)*(10 + 8*n) .* (3.^n) .* (n <= -1);
[z, p, k_gain] = tf2zp(b, a);
x = 3 * sin(n * pi / 3) .* u(n);
y_full = conv(x, h);
n_y = (2*min(n)):(2*max(n)); 
[~, idx_start] = min(abs(n_y - min(n)));
[~, idx_end]   = min(abs(n_y - max(n)));
y = y_full(idx_start:idx_end);
disp('(a) Impulse Response h[n]:');
disp('(b) Difference Equation Representation:');
disp('(c) Poles and Zeros:');
disp('Zeros at :'); disp(z);
disp('Poles at :'); disp(p);
subplot(2,2,1);
zplane(b, a);
title('(c) Pole-Zero Plot (ROC: |z| < 3)');
grid on;
subplot(2,2,2);
stem(n, h, 'filled', 'r');
title('(a) Anti-causal Impulse Response h[n]');
ylabel('amplitude'); xlabel('n--->');
grid on;
subplot(2,2,3);
stem(n, x, 'filled', 'b');
title('(d) Input Signal x[n] = 3 sin(\pi n/3) u[n]');
ylabel('amplitude'); xlabel('n--->');
grid on; axis([-16 16 -3.5 3.5]);
subplot(2,2,4);
stem(n, y, 'filled', 'm');
title('(d) Output Signal y[n] = x[n] * h[n]');
ylabel('amplitude'); xlabel('n--->');
grid on;
