clc; close all; 
a = [1, -1.81, 0.81];
b = [1, 0.5, 0];
[r, p, k] = residuez(b, a);
disp(['r = ' num2str(r')]); 
disp(['p = ' num2str(p')]);
disp(['k = ' num2str(k')]);
[z, p, k] = tf2zp(b, a);
disp('Zeros are at: '); disp(z);
disp('Poles are at: '); disp(p);
disp('Gain constant is: '); disp(k);
zplane(b, a);
title('Pole-Zero Plot');
[H, w] = freqz(b, a);
figure('Name', 'Frequency Response', 'NumberTitle', 'off');
subplot(2,1,1);
plot(w, abs(H), 'LineWidth', 1.2);
title('Magnitude Response');
xlabel('Frequency in Radians');
ylabel('Magnitude');
subplot(2,1,2);
plot(w, angle(H), 'LineWidth', 1.2);
title('Phase Response');
xlabel('Frequency in Radians');
ylabel('Phase Response');
l = 15;
[h_imp, n_imp] = impz(b, a, l);
figure('Name', 'Impulse Response', 'NumberTitle', 'off');
stem(n_imp, h_imp, 'filled');
title('Unit Impulse Response');
xlabel('Sample Number');
ylabel('Amplitude');
grid on;
n = 0:100;
u = n >= 0;
x = 3 * cos(n * pi / 3) .* u;
y = filter(b, a, x);
figure('Name', 'Input and Output Signals', 'NumberTitle', 'off');
subplot(2,1,1); 
plot(n, x, 'LineWidth',1.2); 
title('Input Signal');
subplot(2,1,2); 
plot(n, y, 'LineWidth', 1.2); 
title('Output Signal');
