clc; close all; 
k = 0:15;                
twave = 0:0.001:2;       
fs = 1000;                
tmt = 0:1/fs:0.2;        
x1 = (-1/2).^k;
x2 = (2).^k;
x3 = (-2).^k;
sq25 = square(2*pi*2*twave, 25);
sq50 = square(2*pi*2*twave, 50);
sq75 = square(2*pi*2*twave, 75);
triwave = sawtooth(2*pi*2*twave, 0.5);
multitone = sin(2*pi*10*tmt) + sin(2*pi*30*tmt) + sin(2*pi*60*tmt);
subplot(4,2,1); stem(k, x1); title('(-1/2)^k');
ylabel('amplitude'); xlabel('k--->');
subplot(4,2,2); stem(k, x2); title('(2)^k');
ylabel('amplitude'); xlabel('k--->');
subplot(4,2,3); stem(k, x3); title('(-2)^k');
ylabel('amplitude'); xlabel('k--->'); 
subplot(4,2,4); plot(twave, sq25); title('Square Wave: 25% Duty');
ylabel('amplitude'); xlabel('t--->');
subplot(4,2,5); plot(twave, sq50); title('Square Wave: 50% Duty');
ylabel('amplitude'); xlabel('t--->'); 
subplot(4,2,6); plot(twave, sq75); title('Square Wave: 75% Duty');
ylabel('amplitude'); xlabel('t--->'); 
subplot(4,2,7); plot(twave, triwave); title('Triangular Wave');
ylabel('amplitude'); xlabel('t--->');
subplot(4,2,8); plot(tmt, multitone); title('Multitone signal');
ylabel('amplitude'); xlabel('t (s)--->');
