clc; close all;
n = -10:10;
u = n >= 0; 
u3 = (n - 3) >= 0;
xa = u - u3;
xb = sin(n*pi/3) .* u;
xc = (0.5.^n) .* exp(1i * pi * n / 2);
magc = abs(xc);      
phasec = angle(xc);  
subplot(2,2,1); stem(n, xa, 'filled');
title('x[n] = u[n] - u[n-3]');
ylabel('amplitude'); xlabel('n--->');
subplot(2,2,2); stem(n, xb, 'filled');
title('x[n] = sin(n\pi/3) u[n]');
ylabel('amplitude'); xlabel('n--->');
subplot(2,2,3); stem(n, magc, 'filled');
title('x[n] = 0.5^n e^{j\pi n/2} (Magnitude)');
ylabel('|x[n]|'); xlabel('n--->');
subplot(2,2,4); stem(n, phasec, 'filled');
title('x[n] = 0.5^n e^{j\pi n/2} (Phase Angle)');
ylabel('angle (radians)'); xlabel('n--->');
