clc; close all; clearvars;
n = -5:110;
u = @(n) (n >= 0); 
xa = 5 * (u(n) - u(n-20));
xb = (u(n) - u(n-10)) + (20 - n) .* (u(n-10) - (n-20));
xc = sin(pi * n / 25) .* (u(n) - u(n-100));
ya = xa - [0, xa(1:end-1)];
yb = xb - [0, xb(1:end-1)];
yc = xc - [0, xc(1:end-1)];
subplot(3,2,1); stem(n, xa, 'filled'); title('Input: x[n] = 5(u[n] - u[n-20])');
ylabel('amplitude'); xlabel('n--->');
subplot(3,2,2); stem(n, ya, 'filled'); title('Output: y[n] = x[n] - x[n-1]');
ylabel('amplitude'); xlabel('n--->'); 
subplot(3,2,3); stem(n, xb, 'filled'); title('Input: x[n] = (u[n] - u[n-10]) + (20-n)(u[n-10] - [n-20])');
ylabel('amplitude'); xlabel('n--->');
subplot(3,2,4); stem(n, yb, 'filled'); title('Output: y[n] = x[n] - x[n-1]');
ylabel('amplitude'); xlabel('n--->');
subplot(3,2,5); stem(n, xc, 'filled'); title('Input: x[n] = sin(\pi n/25)(u[n] - u[n-100])');
ylabel('amplitude'); xlabel('n--->');
subplot(3,2,6); stem(n, yc, 'filled'); title('Output: y[n] = x[n] - x[n-1]');
ylabel('amplitude'); xlabel('n--->'); 
