originalImage = imread('peppers.png');
rot90Image = imrotate(originalImage, 90);
rot180Image = imrotate(originalImage, 180);
flipHorizImage = fliplr(originalImage);
flipVertImage = flipud(originalImage);  
subplot(2, 3, 1);
imshow(originalImage);
title('Original Image');
subplot(2, 3, 2);
imshow(rot90Image);
title('Rotated by 90');
subplot(2, 3, 3);
imshow(rot180Image);
title('Rotated by 180');
subplot(2, 3, 4);
imshow(flipHorizImage);
title('Flipped Horizontally');
subplot(2, 3, 5);
imshow(flipVertImage);
title('Flipped Vertically');
subplot(2, 3, 6);
axis off;
