clc; close all; 
T = 0.1;                      
Fs = 1/T;                      
b_s = [1, 1];                 
a_s = [1, 5, 1];             
[b_z, a_z] = impinvar(b_s, a_s, Fs);
fprintf('Numerator b_z   : [%.6f, %.6f, %.6f]\n', b_z);
fprintf('Denominator a_z : [%.6f, %.6f, %.6f]\n', a_z);
f = linspace(0, Fs/2, 2000);
w_analog = 2 * pi * f;
h_s = freqs(b_s, a_s, w_analog);
[h_z, w_digital] = freqz(b_z, a_z, 2000, Fs);
subplot(2,1,1);
plot(f, abs(h_s)/T, 'Color', '#00FFFF', 'LineWidth', 2); hold on; 
plot(w_digital, abs(h_z), '--', 'Color', '#00FF66', 'LineWidth', 1.8);
title('Magnitude Response Comparison (Linear Scale)');
xlabel('Frequency (Hz)'); ylabel('Magnitude |H(f)|');
legend('Analog |H(j\omega)| / T', 'Digital |H(e^{j\omega T})|', 'Location', 'northeast');
xlim([0 Fs/2]);
subplot(2,1,2);
plot(f, 20*log10(abs(h_s)/T), 'Color', '#00FFFF', 'LineWidth', 2); hold on;
plot(w_digital, 20*log10(abs(h_z)), '--', 'Color', '#00FF66', 'LineWidth', 1.8);
title('Magnitude Response Comparison (dB Scale)');
xlabel('Frequency (Hz)'); ylabel('Magnitude (dB)');
legend('Analog |H(j\omega)| / T', 'Digital |H(e^{j\omega T})|', 'Location', 'southwest');
xlim([0 Fs/2]);
