clc; close all; 
wp = 0.3*pi; ws = 0.5*pi; Rp = 1; Rs = 20; T = 1; Fs = 1/T;
[n1, Wp1] = cheb1ord(wp/T, ws/T, Rp, Rs, 's');
[b_s1, a_s1] = cheby1(n1, Rp, Wp1, 's');
[b1, a1] = impinvar(b_s1, a_s1, Fs);
[n2, Ws2] = cheb2ord(wp/T, ws/T, Rp, Rs, 's');
[b_s2, a_s2] = cheby2(n2, Rs, Ws2, 's');
[b2, a2] = impinvar(b_s2, a_s2, Fs);
[ne, Wpe] = ellipord(wp/T, ws/T, Rp, Rs, 's');
[b_se, a_se] = ellip(ne, Rp, Rs, Wpe, 's');
[be, ae] = impinvar(b_se, a_se, Fs);
[H1, w] = freqz(b1, a1, 1024); H2 = freqz(b2, a2, 1024); He = freqz(be, ae, 1024);
figure('Name', 'Filter Comparison', 'NumberTitle', 'off');
subplot(2,1,1);
plot(w/pi, 20*log10(abs([H1 H2 He])), 'LineWidth', 1.8); grid on;
title('Magnitude Response (dB)'); ylabel('dB'); xlabel('\omega (\times\pi rad)');
legend(sprintf('Cheb-I (N=%d)', n1), sprintf('Cheb-II (N=%d)', n2), sprintf('Elliptic (N=%d)', ne));
colororder({'#00FFFF', '#00FF66', '#FF9900'}); 
subplot(2,1,2);
plot(w/pi, abs([H1 H2 He]), 'LineWidth', 1.8); grid on;
title('Magnitude Response (Linear)'); ylabel('|H(e^{j\omega})|'); xlabel('\omega (\times\pi rad)');
legend(sprintf('Cheb-I (N=%d)', n1), sprintf('Cheb-II (N=%d)', n2), sprintf('Elliptic (N=%d)', ne));
colororder({'#00FFFF', '#00FF66', '#FF9900'});
